services:
  frontend:
    image: aarsh2101/personalized-migrant-resource-route-frontend:latest
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production

  backend:
    image: aarsh2101/personalized-migrant-resource-route-backend:latest
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      GEOCODE_API_KEY: ${GEOCODE_API_KEY}
      ORS_API_KEY: ${ORS_API_KEY}
