services:
  frontend:
    platform: linux/amd64
    pull_policy: always
    image: aarsh2101/personalized-migrant-resource-route-frontend:latest
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production

  backend:
    platform: linux/amd64
    pull_policy: always
    image: aarsh2101/personalized-migrant-resource-route-backend:latest
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      CUSTOMCONNSTR_GEOCODE_API_KEY: ${CUSTOMCONNSTR_GEOCODE_API_KEY}
      CUSTOMCONNSTR_ORS_API_KEY: ${CUSTOMCONNSTR_ORS_API_KEY}
